ctms/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf import settings

from authentication import views as views
from vehicle import views as v_views
from driver import views as d_views
from accidents import views as a_views
from gpsdevices import views as as_views

urlpatterns = [
   # url(r'^django_popup_view_field/', include('django_popup_view_field.urls', namespace="django_popup_view_field")),

   url(r'^$', auth_views.login, {'template_name': 'login.html'}, name='login'),
   url(r'^home$', views.index, name='index'),
   url(r'^location$', views.location, name='location'),
   url(r'^route$', views.route, name='routes'),
   url(r'^report$', views.report, name='reports'),
   url(r'^schedule$', views.schedule, name='schedules'),

   url(r'^vehicles_list/$', v_views.VehicleListView.as_view(), name='vehicles_list'),
   url(r'^add_vehicle/$', v_views.CreateVehicleView.as_view(), name='add_vehicle'),
   url(r'^edit_vehicle/(?P<pk>\d+)/$', v_views.UpdateVehicleView.as_view(), name='edit_vehicle'),
   url(r'^view_vehicle/(?P<pk>\d+)/$', v_views.VehicleView.as_view(), name='view_vehicle'),
   # url(r'^view_vehicle/(?P<pk>\d+)/$', v_views.view_vehicle, name='view_vehicle'),
   url(r'^delete_vehicle/(?P<pk>\d+)/$', v_views.DeleteVehicleView.as_view(), name='delete_vehicle'),
   # url(r'^records_list/$', v_views.MonthlyListView.as_view(), name='records_list'),
   # url(r'^add_record/$', v_views.CreateMonthlyView.as_view(), name='add_record'),
   # url(r'^edit_record/(?P<pk>\d+)/$', v_views.UpdateMonthlyView.as_view(), name='edit_record'),
   # url(r'^record/(?P<pk>\d+)/$', v_views.MonthlyView.as_view(), name='view_record'),

   url(r'^drivers_list/$', d_views.DriverListView.as_view(), name='drivers_list'),
   url(r'^add_driver/$',d_views.CreateDriverView.as_view(), name='add_driver'),
   url(r'^edit_driver/(?P<pk>\d+)/$', d_views.UpdateDriverView.as_view(), name='edit_driver'),
   url(r'^driver/(?P<pk>\d+)/$', d_views.DriverView.as_view(), name='view_driver'),
   url(r'^delete_driver/(?P<pk>\d+)/$', d_views.DeleteDriverView.as_view(), name='delete_driver'),

   url(r'^gpsdevices_list/$', as_views.GPSDeviceListView.as_view(), name='gpsdevices_list'),
   url(r'^add_gpsdevice/$', as_views.CreateGPSDeviceView.as_view(), name='add_gpsdevice'),
   url(r'^edit_gpsdevice/(?P<pk>\d+)/$', as_views.UpdateGPSDeviceView.as_view(), name='edit_gpsdevice'),
   url(r'^gpsdevice/(?P<pk>\d+)/$', as_views.GPSDeviceView.as_view(), name='gpsdevice'),
   url(r'^view_gpsdevice/(?P<pk>\d+)/$', as_views.view_gpsdevice, name='view_gpsdevice'),

   url(r'^accidents_list/$', a_views.AccidentsListView.as_view(), name='accidents_list'),
   url(r'^add_accident/$', a_views.CreateAccidentView.as_view(), name='add_accident'),
   url(r'^edit_accident/(?P<pk>\d+)/$', a_views.UpdateAccidentView.as_view(), name='edit_accident'),
   url(r'^delete_accident/(?P<pk>\d+)/$', a_views.DeleteAccidentView.as_view(), name='delete_accident'),
   url(r'^accident/(?P<pk>\d+)/$', a_views.AccidentView.as_view(), name='view_accident'),
   url(r'^accidents/(?P<pk>\d+)/$', a_views.accidentsView, name='accidents'),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

generic_views/forms.py
import types

from django import forms
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext as _
from django.db import models

from ctms import settings


def return_attrib(obj, attrib, arguments=None):
    try:
        from functools import reduce
        result = reduce(getattr, attrib.split('.'), obj)
        if isinstance(result, types.MethodType):
            if arguments:
                return result(**arguments)
            else:
                return result()
        else:
            return result
    except Exception as err:
        if settings.DEBUG:
            return 'Attribute error: %s; %s' % (attrib, err)
        else:
            pass


class DetailSelectMultiple(forms.widgets.SelectMultiple):
    def __init__(self, queryset=None, *args, **kwargs):
        self.queryset=queryset
        super(DetailSelectMultiple, self).__init__(*args, **kwargs)

    def render(self, name, value, attrs=None, choices=()):
        if value is None: value = ''
        #final_attrs = self.build_attrs(attrs, name=name)
        output = u'<ul class="list">'
        options = None
        if value:
            if getattr(value, '__iter__', None):
                options = [(index, string) for index, string in self.choices if index in value]
            else:
                options = [(index, string) for index, string in self.choices if index == value]
        else:
            if self.choices:
                if self.choices[0] != (u'', u'---------') and value != []:
                    options = [(index, string) for index, string in self.choices]

        if options:
            for index, string in options:
                if self.queryset:
                    try:
                        output += u'<li><a href="%s">%s</a></li>' % (self.queryset.get(pk=index).get_absolute_url(), string)
                    except AttributeError:
                        output += u'<li>%s</li>' % (string)
                else:
                 output += u'<li>%s</li>' % string
        else:
            output += u'<li>%s</li>' % _(u"None")
        return mark_safe(output + u'</ul>\n')


class DetailForm(forms.ModelForm):
    def __init__(self, extra_fields=None, *args, **kwargs):
        super(DetailForm, self).__init__(*args, **kwargs)
        if extra_fields:
            for extra_field in extra_fields:
                result = return_attrib(self.instance, extra_field['field'])
                label = 'label' in extra_field and extra_field['label'] or None
                #TODO: Add others result types <=> Field types
                if isinstance(result, models.query.QuerySet):
                    self.fields[extra_field['field']]=forms.ModelMultipleChoiceField(queryset=result, label=label)

        for field_name, field in self.fields.items():
            if isinstance(field.widget, forms.widgets.SelectMultiple):
                self.fields[field_name].widget = DetailSelectMultiple(
                    choices=field.widget.choices,
                    attrs=field.widget.attrs,
                    queryset=getattr(field, 'queryset', None),
                )
                self.fields[field_name].help_text=''
            elif isinstance(field.widget, forms.widgets.Select):
                self.fields[field_name].widget = DetailSelectMultiple(
                    choices=field.widget.choices,
                    attrs=field.widget.attrs,
                    queryset=getattr(field, 'queryset', None),
                )
                self.fields[field_name].help_text=''


class GenericConfirmForm(forms.Form):
    pass


class GenericAssignRemoveForm(forms.Form):
    left_list = forms.ModelMultipleChoiceField(required=False, queryset=None)
    right_list = forms.ModelMultipleChoiceField(required=False, queryset=None)
    def __init__(self, left_list_qryset=None, right_list_qryset=None, left_filter=None, *args, **kwargs):
        super(GenericAssignRemoveForm, self).__init__(*args, **kwargs)
        if left_filter:
            self.fields['left_list'].queryset = left_list_qryset.filter(*left_filter)
        else:
            self.fields['left_list'].queryset = left_list_qryset

        self.fields['right_list'].queryset = right_list_qryset


class FilterForm(forms.Form):
    def __init__(self, list_filters, *args, **kwargs):
        super(FilterForm, self).__init__(*args, **kwargs)
        for list_filter in list_filters:
            label = list_filter.get('title', list_filter['name'])
            self.fields[list_filter['name']] = forms.ModelChoiceField(queryset=list_filter['queryset'], label=label[0].upper() + label[1:], required=False)

generic_views/views.py
from __future__ import absolute_import

import urllib

from django.core.urlresolvers import reverse, NoReverseMatch
from django.contrib import messages
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.utils.translation import ugettext as _
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from .forms import (FilterForm, GenericConfirmForm, GenericAssignRemoveForm,
                    DetailForm)


class ExtraContextMixin(object):
    extra_context = {}

    def get_context_data(self, **kwargs):
        context = super(ExtraContextMixin, self).get_context_data(**kwargs)
        context.update(self.extra_context)
        return context


class GenericCreateView(ExtraContextMixin, CreateView):
    template_name = 'generic_views/generic_form.html'


class GenericDeleteView(ExtraContextMixin, DeleteView):
    template_name='generic_views/generic_confirm.html'

    def get_context_data(self, **kwargs):
        context = super(GenericDeleteView, self).get_context_data(**kwargs)
        context['delete_view'] = True
        return context

    #kwargs['post_delete_redirect'] = reverse(kwargs['post_delete_redirect'])


class GenericDetailView(ExtraContextMixin, DetailView):
    template_name = 'generic_views/generic_detail.html'

    def get_context_data(self, **kwargs):
        context = super(GenericDetailView, self).get_context_data(**kwargs)
        if hasattr(self, 'extra_fields'):
            context['form'] = self.form_class(instance=self.get_object(), extra_fields=getattr(self, 'extra_fields', None))
        else:
            context['form'] = self.form_class(instance=self.get_object())

        return context


class GenericListView(ExtraContextMixin, ListView):
    filter_form = None
    filters = None
    list_filters = None
    template_name = 'generic_views/generic_list.html'

    def get(self, request, *args, **kwargs):
        if self.list_filters:
            self.filter_form, self.filters = add_filter(self.request, self.list_filters)
        return super(GenericListView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(GenericListView, self).get_context_data(**kwargs)

        if self.filter_form:
            context['filter_form'] = self.filter_form

        return context

    def get_queryset(self):
        queryset = super(GenericListView, self).get_queryset()
        if self.filters:
            return queryset.filter(*self.filters)
        else:
            return queryset


class GenericUpdateView(ExtraContextMixin, UpdateView):
    template_name = 'generic_views/generic_form.html'


def add_filter(request, list_filters):
    filters = []
    filter_dict = dict([(f['name'], f) for f in list_filters])
    if request.method == 'GET':
        filter_form = FilterForm(list_filters, request.GET)
        if filter_form.is_valid():
            for name, data in filter_form.cleaned_data.items():
                if data:
                    filters.append(Q(**{filter_dict[name]['destination']: data}))

    else:
        filter_form = FilterForm(list_filters)

    return filter_form, filters


def generic_assign_remove(request, title, obj, left_list_qryset, left_list_title, right_list_qryset, right_list_title, add_method, remove_method, item_name, list_filter=None):
    left_filter = None
    filter_form = None
    if list_filter:
        filter_form, filters = add_filter(request, list_filter)
        if filters:
            left_filter = filters

    if request.method == 'POST':
        post_data = request.POST
        form = GenericAssignRemoveForm(left_list_qryset, right_list_qryset, left_filter, request.POST)
        if form.is_valid():
            action = post_data.get('action','')
            if action == 'assign':
                for item in form.cleaned_data['left_list']:
                    add_method(item)
                if form.cleaned_data['left_list']:
                    messages.success(request, _(u'The selected %s were added.') % unicode(item_name))

            if action == 'remove':
                for item in form.cleaned_data['right_list']:
                    remove_method(item)
                if form.cleaned_data['right_list']:
                    messages.success(request, _(u'The selected %s were removed.') % unicode(item_name))

    form = GenericAssignRemoveForm(left_list_qryset=left_list_qryset, right_list_qryset=right_list_qryset, left_filter=left_filter)

    return render_to_response('generic_views/generic_assign_remove.html', {
    'form': form,
    'object': obj,
    'title': title,
    'left_list_title': left_list_title,
    'right_list_title': right_list_title,
    'filter_form': filter_form,
    },
    context_instance=RequestContext(request))

generic_views/templates/generic_views/calculate_form_title.html
{% load i18n %}

{% if title %}
    {% if striptags %}
        {{ title|striptags }}
    {% else %}
        {{ title|safe }}
    {% endif %}
{% else %}
    {% if read_only %}
        {% if object_name %}
            {% blocktrans %}Details for: {{ object_name }}: {{ object }}{% endblocktrans %}
        {% else %}
            {% blocktrans %}Details for: {{ object }}{% endblocktrans %}
        {% endif %}
    {% else %}
        {% if object %}
            {% if object_name %}
                {% blocktrans %}Edit: {{ object_name }}:{% endblocktrans %} {% if not striptags %}<a href="{{ object.get_absolute_url }}">{% endif %}{{ object }}{% if not striptags %}</a>{% endif %}
            {% else %}
                {% trans 'Edit' %}: {% if not striptags %}<a href="{{ object.get_absolute_url }}">{% endif %}{{ object }}{% if not striptags %}</a>{% endif %}
            {% endif %}
        {% else %}
            {% if object_name %}
                {% blocktrans %}Create new: {{ object_name }}{% endblocktrans %}
            {% else %}
                {% trans 'Create' %}
            {% endif %}
        {% endif %}
    {% endif %}
{% endif %}

generic_views/templates/generic_views/generic_assign_remove.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %} :: {% blocktrans %}Assign {{ title }} {{ object }}{% endblocktrans %}{% endblock %}

{% block content %}
    <style>
        #id_right_list,#id_left_list { min-width: 28em; min-height: 13em; }
    </style>
    <div class="content">
        <h2 class="title">{{ title|safe }}</h2>

        <form method='POST' action='' id='assign_remove'>{% csrf_token %}
            <input name='action' value='' type='hidden' />
             <table>
                <tbody>
                    <tr>
                        <th style='text-align:center;'>{{ left_list_title }}</th><td></td><th style='text-align:center;'>{{ right_list_title }}</th>
                    </tr>
                    <tr>
                        <td>
                            {{ form.left_list }}{{ form.left_list.errors }}
                        </td>
                        <td>
                            <table>
                                <tbody>
                                    <tr>
                                      <td><button class="button" onclick='document.forms["assign_remove"].action.value="assign";document.forms["assign_remove"].submit();'>&gt;</button></td>
                                    </tr>
                                    <tr>
                                      <td><button class="button" onclick='document.forms["assign_remove"].action.value="remove";document.forms["assign_remove"].submit();'>&lt;</button></td>
                                    </tr>
                                </tbody>
                            </table>
                        </td>
                        <td>{{ form.right_list }}{{ form.right_list.errors }}</td>
                    </tr>
                    {{ form.media|safe }}
                </tbody>
            </table>
        </form>
    </div>
{% endblock %}

generic_views/templates/generic_views/generic_confirm.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}

{% block title %} :: {% if delete_view %}{% trans 'Confirm delete' %}{% else %}{% trans 'Confirm' %}{% endif %}{% endblock %}

{% block sidebar %}
    {% for subtemplate in subtemplates %}
        {% include subtemplate %}
    {% endfor %}
{% endblock %}

{% block content %}
    <div id="box">
      <div class="block" id="block-login">
        {% if delete_view %}
            <h2>{% trans 'Confirm delete' %}</h2>
        {% else %}
            <h2>{% trans 'Confirm' %}</h2>
        {% endif %}
        <div class="content login">
          <form action="" method="post" class="form login">{% csrf_token %}
            {% if next %}
                <input name="next" type="hidden" value="{{ next }}" />
            {% endif %}

            {% if title %}
                <h3>{{ title }}</h3>
            {% else %}
                {% if delete_view %}
                    {% if object_name %}
                        <h3>{% blocktrans %}Are you sure you wish to delete {{ object_name }}: {{ object }}?{% endblocktrans %}</h3>
                    {% else %}
                        <h3>{% blocktrans %}Are you sure you wish to delete: {{ object }}?{% endblocktrans %}</h3>
                    {% endif %}
                {% else %}
                    <h4>{% trans 'Are you sure you wish to proceed?' %}</h4>
                {% endif %}
            {% endif %}
            {% if message %}<h4>{{ message }}</h4>{% endif %}

            <div class="group navform wat-cf">
                <button class="button" type="submit">
                    <img src="{% static 'web_theme_media/images/icons/tick.png' %}" alt="{% trans 'Yes' %}" /> {% trans 'Yes' %}
                </button>
                <a href="#" onclick='{% if previous %}window.location.replace("{{ previous }}");{% else %}history.go(-2);{% endif %}' class="button">
                    <img src="{% static 'web_theme_media/images/icons/cross.png' %}"  alt="{% trans 'No' %}"/> {% trans 'No' %}
                </a>
            </div>
          </form>
        </div>
      </div>
    </div>
{% endblock %}

generic_views/templates/generic_views/generic_detail.html
{% extends 'base.html' %}

{% load i18n %}

{% load styling %}
{% load generic_views_helpers %}

{% block title %} :: {% with 'true' as read_only %}{% with 'true' as striptags %}{% include 'generic_views/calculate_form_title.html' %}{% endwith %}{% endwith %}{% endblock %}

{% block javascript %}
    <script type="text/javascript">
    $(function() {
        $('#subform form :input').each(function() {
            this.disabled = true;
        });
    });
    </script>
{% endblock %}

{% block sidebar %}
    {% for subtemplate in sidebar_subtemplates %}
        {% include subtemplate %}
    {% endfor %}
{% endblock %}

{% block stylesheets %}
    <style type="text/css">
        #subform form  textarea,
        #subform form  select option,
        #subform form  input,
        #subform form  select,
        #subform form  input { background: none; color: black; border: none; }
    </style>
{% endblock %}

{% block content %}
    <div id="subform">
        {% with "true" as read_only %}
            {% include 'generic_views/generic_form_subtemplate.html' %}
        {% endwith %}
    </div>

    {% for subtemplate in subtemplates %}
        {% include subtemplate %}
    {% endfor %}

    {% for subtemplate in subtemplates_dict %}
    {% with subtemplate.title as title %}
    {% with subtemplate.object_list as object_list %}
    {% with subtemplate.extra_columns as extra_columns %}
    {% with subtemplate.hide_object as hide_object %}
    {% with subtemplate.main_object as main_object %}
        {% include subtemplate.name %}
    {% endwith %}
    {% endwith %}
    {% endwith %}
    {% endwith %}
    {% endwith %}
    {% endfor %}

{% endblock %}

generic_views/templates/generic_views/generic_form.html
{% extends 'base.html' %}

{% block title %} :: {% with 'true' as striptags %}{% include 'generic_views/calculate_form_title.html' %}{% endwith %}{% endblock %}

{% block content %}
    {% include 'generic_views/generic_form_subtemplate.html' %}
{% endblock %}

generic_views/templates/generic_views/generic_form_instance.html
{% load i18n %}

{% load styling %}

{{ form.media|safe }}

{% add_classes_to_form form %}

{% if form.non_field_errors %}
    <div class="flash">
        {% for value in form.non_field_errors %}
            <div class="message error">
                <p>{{ value }}</p>
            </div>
      {% endfor %}
  </div>
{% endif %}

{% if form_display_mode_table %}
    {% for field in form.hidden_fields %}
        {{ field }}
    {% endfor %}
    <tr class="{% cycle 'odd' 'even2' %}">
    {% for field in form.visible_fields %}
            <td title="{% if field.errors %}{% for error in field.errors %}{{ error }}{% if not forloop.last %} | {% endif %}{% endfor %}{% else %}{{ field.help_text }}{% endif %}">
            {% if field.errors %}<div class="flash"><div class="error">{% endif %}
              {{ field }}
            {% if field.errors %}</div></div>{% endif %}
            </td>
    {% endfor %}
    </tr>
{% else %}
    {% for field in form %}
        <div class="group">
            {% if field.errors %}<div class="fieldWithErrors">{% endif %}
            <label class="label">{{ field.label_tag }}{% if field.field.required and not read_only %} ({% trans 'required' %}){% endif %}</label>
            {% if field.errors %}<span class="error">{% for error in field.errors %}{{ error }}{% if not forloop.last %} | {% endif %}{% endfor %}</span></div>{% endif %}
            {{ field }}
            {% if field.help_text %}<span class="description">{{ field.help_text }}</span>{% endif %}
        </div>
    {% endfor %}
{% endif %}

generic_views/templates/generic_views/generic_form_subtemplate.html
{% load i18n %}
{% load static %}

{% if side_bar %}
    <div class="block">
    <h3>
{% else %}
    <div class="content">
    <h2 class="title">
{% endif %}

{% include 'generic_views/calculate_form_title.html' %}

{% if side_bar %}
    </h3>
    <div class="content">
        <p>
{% else %}
    </h2>
    <div class="inner">
{% endif %}

    {% if form.is_multipart %}
        <form enctype="multipart/form-data" method="{{ submit_method|default:'post' }}" action="" class="form">
    {% else %}
        <form method="{{ submit_method|default:'post' }}" action="" class="form">
    {% endif %}
        {% if step_field %}
            <input type="hidden" name="{{ step_field }}" value="{{ step0 }}" />
        {% endif %}

        {% if submit_method != 'GET' and submit_method != 'get' %}
            {% csrf_token %}
        {% endif %}

        {% for hidden_field in hidden_fields %}
           {{ hidden_field.as_hidden }}
        {% endfor %}

        {% if form.management_form %}
            {% with form as formset %}
                {{ formset.management_form }}

                {% if form_display_mode_table %}
                    <table class="table">
                        <tbody>
                        <tr>
                            {% for field in formset.forms.0.visible_fields %}
                                <th>
                                    {{ field.label_tag }}{% if field.field.required and not read_only %} ({% trans 'required' %}){% endif %}
                                </th>
                            {#{% if field.help_text %}<span class="description">{{ field.help_text }}</span>{% endif %}#}
                            {% endfor %}
                        </tr>
                {% endif %}

                {% for form in formset.forms %}
                    {% include 'generic_views/generic_form_instance.html' %}
                {% endfor %}
                {% if form_display_mode_table %}
                    </tbody>
                    </table>
                {% endif %}
            {% endwith %}
        {% else %}
            {% include 'generic_views/generic_form_instance.html' %}
        {% endif %}

        {% if not read_only %}
        <div class="group navform wat-cf">
            <button class="button" type="submit">
                <img src="{% static 'web_theme_media/images/icons/tick.png' %}" alt="{% if object %}{% trans 'Save' %}{% else %}{% trans 'Submit' %}{% endif %}" /> {% if object %}{% trans 'Save' %}{% else %}{% trans 'Submit' %}{% endif %}
            </button>
            {% comment %}
            <a href="#header" class="button">
                <img src="{% static 'web_theme_media/images/icons/cross.png' %}" alt="{% trans 'Cancel' %}"/> {% trans 'Cancel' %}
            </a>
            {% endcomment %}
        </div>
        {% endif %}
    </form>
    {% if sidebar %}
        </p></div></div>
    {% else %}
        </div></div>
    {% endif %}

generic_views/templates/generic_views/generic_list.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %} :: {{ title }}{% endblock %}

{% block content %}
    {% include 'generic_views/generic_list_subtemplate.html' %}
{% endblock %}

generic_views/templates/generic_views/generic_list_subtemplate.html
{% load i18n %}

{% load generic_views_helpers %}
{% load pagination_tags %}
{% load navigation %}

{% if side_bar %}
    <div class="block">
    <h3>
        {{ title }}
    </h3>
    <div class="content">
        <p>
{% else %}
    {% autopaginate object_list %}
    <div class="content">
    <h2 class="title">
        {% ifnotequal page_obj.paginator.num_pages 1 %}
            {% blocktrans with page_obj.start_index as start and page_obj.end_index as end and page_obj.paginator.object_list|length as total %}{{ title }} ({{ start }} - {{ end }} out of {{ total }}){% endblocktrans %}
        {% else %}
            {% blocktrans with page_obj.paginator.object_list|length as total %}{{ title }} ({{ total }}){% endblocktrans %}
        {% endifnotequal %}
    </h2>

<div class="inner">
{% endif %}

  <form action="#" class="form">
    <table class="table">
    <tbody>
      {% if not hide_header %}
          <tr>
            {% if not hide_object %}
                <th>{% trans 'Identifier' %}</th>
            {% endif %}
            {% for column in extra_columns %}
                <th>{{ column.name|capfirst }}</th>
            {% endfor %}
            {% if not hide_links %}
                <th class="">&nbsp;</th>
            {% endif %}
          </tr>
      {% endif %}
        {% for object in object_list %}
            <tr class="{% cycle 'odd' 'even2' %}">
            {% if not hide_object %}
                {% if main_object %}
                    {% with object|object_property:main_object as object %}
                        <td>{% if not hide_link %}<a href="{{ object.get_absolute_url }}">{{ object }}</a>{% else %}{{ object }}{% endif %}</td>
                    {% endwith %}
                {% else %}
                    <td>{% if not hide_link %}<a href="{{ object.get_absolute_url }}">{{ object }}</a>{% else %}{{ object }}{% endif %}</td>
                {% endif %}
            {% endif %}
                {% for column in extra_columns %}
                    <td>{{ object|object_property:column.attribute|safe }}</td>
                {% endfor %}
                {% if not hide_links %}
                    <td class='last'>
                        {% object_navigation_template %}
                    </td>
                {% endif %}
            </tr>
        {% empty %}
            <tr><td colspan=99 class="tc">{% trans 'No results' %}</td></tr>
        {% endfor %}
        </tbody>
    </table>
  </form>
    {% paginate %}
</div>
</div>

    {% for subform in subforms_dict %}
    {% with subform.title as title %}
    {% with subform.extra_columns as extra_columns %}
    {% with subform.form as form %}
        {% include subform.name %}
    {% endwith %}
    {% endwith %}
    {% endwith %}
    {% endfor %}

generic_views/templates/generic_views/generic_navigation.html
{% load i18n %}

{% for link in object_navigation_links %}
    {% if as_li %}<li>{% endif %}
        <a href="{{ link.url }}">{% if link.famfam %}<span class="famfam active famfam-{{ link.famfam|default:'link' }}"></span>{% endif %}{{ link.text|capfirst }}{% if link.error %} - {{ link.error }}{% endif %}{% if link.active %}<span class="famfam active famfam-resultset_previous"></span>{% endif %}</a>{% if horizontal %}{% if not forloop.last %} | {% endif %}{% endif %}
    {% if as_li %}</li>{% endif %}    
{% endfor %}