ctms/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf import settings

from authentication import views as views
from vehicle import views as v_views
from driver import views as d_views
from accidents import views as a_views
from gpsdevices import views as as_views

urlpatterns = [
   # url(r'^django_popup_view_field/', include('django_popup_view_field.urls', namespace="django_popup_view_field")),

   url(r'^$', auth_views.login, {'template_name': 'login.html'}, name='login'),
   url(r'^home$', views.index, name='index'),
   url(r'^location$', views.location, name='location'),
   url(r'^route$', views.route, name='routes'),
   url(r'^report$', views.report, name='reports'),
   url(r'^schedule$', views.schedule, name='schedules'),

   url(r'^vehicles_list/$', v_views.VehicleListView.as_view(), name='vehicles_list'),
   url(r'^add_vehicle/$', v_views.CreateVehicleView.as_view(), name='add_vehicle'),
   url(r'^edit_vehicle/(?P<pk>\d+)/$', v_views.UpdateVehicleView.as_view(), name='edit_vehicle'),
   url(r'^view_vehicle/(?P<pk>\d+)/$', v_views.VehicleView.as_view(), name='view_vehicle'),
   # url(r'^view_vehicle/(?P<pk>\d+)/$', v_views.view_vehicle, name='view_vehicle'),
   url(r'^delete_vehicle/(?P<pk>\d+)/$', v_views.DeleteVehicleView.as_view(), name='delete_vehicle'),
   # url(r'^records_list/$', v_views.MonthlyListView.as_view(), name='records_list'),
   # url(r'^add_record/$', v_views.CreateMonthlyView.as_view(), name='add_record'),
   # url(r'^edit_record/(?P<pk>\d+)/$', v_views.UpdateMonthlyView.as_view(), name='edit_record'),
   # url(r'^record/(?P<pk>\d+)/$', v_views.MonthlyView.as_view(), name='view_record'),

   url(r'^drivers_list/$', d_views.DriverListView.as_view(), name='drivers_list'),
   url(r'^add_driver/$',d_views.CreateDriverView.as_view(), name='add_driver'),
   url(r'^edit_driver/(?P<pk>\d+)/$', d_views.UpdateDriverView.as_view(), name='edit_driver'),
   url(r'^driver/(?P<pk>\d+)/$', d_views.DriverView.as_view(), name='view_driver'),
   url(r'^delete_driver/(?P<pk>\d+)/$', d_views.DeleteDriverView.as_view(), name='delete_driver'),

   url(r'^gpsdevices_list/$', as_views.GPSDeviceListView.as_view(), name='gpsdevices_list'),
   url(r'^add_gpsdevice/$', as_views.CreateGPSDeviceView.as_view(), name='add_gpsdevice'),
   url(r'^edit_gpsdevice/(?P<pk>\d+)/$', as_views.UpdateGPSDeviceView.as_view(), name='edit_gpsdevice'),
   url(r'^gpsdevice/(?P<pk>\d+)/$', as_views.GPSDeviceView.as_view(), name='gpsdevice'),
   url(r'^view_gpsdevice/(?P<pk>\d+)/$', as_views.view_gpsdevice, name='view_gpsdevice'),

   url(r'^accidents_list/$', a_views.AccidentsListView.as_view(), name='accidents_list'),
   url(r'^add_accident/$', a_views.CreateAccidentView.as_view(), name='add_accident'),
   url(r'^edit_accident/(?P<pk>\d+)/$', a_views.UpdateAccidentView.as_view(), name='edit_accident'),
   url(r'^delete_accident/(?P<pk>\d+)/$', a_views.DeleteAccidentView.as_view(), name='delete_accident'),
   url(r'^accident/(?P<pk>\d+)/$', a_views.AccidentView.as_view(), name='view_accident'),
   url(r'^accidents/(?P<pk>\d+)/$', a_views.accidentsView, name='accidents'),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gpsdevices/models.py
from __future__ import unicode_literals

from django.utils.translation import ugettext as _
from django.contrib.auth.models import User
from django.db import models
from vehicle.models import Vehicle


class GPSDevice(models.Model):

    name = models.CharField(max_length=30)
    type = models.CharField(max_length=30)
    imei = models.CharField(max_length=30)
    sim_num = models.CharField(max_length=30)
    purchase_date = models.DateField(max_length=30)
    assigned_to = models.CharField(max_length=30)
    status = models.CharField(max_length=30)

    class Meta:
        unique_together = ("name", "imei", "sim_num")
        ordering = ['purchase_date']
        verbose_name = _(u'GPSDevice')
        verbose_name_plural = _(u'GPSDevices')

    def __str__(self):
        return self.name + " " + self.imei + " " + self.sim_num

vehicle/models.py
from __future__ import unicode_literals

from datetime import datetime

from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _
from driver.models import Driver


class Vehicle(models.Model):

    licence_num = models.CharField(default=None, max_length=30, verbose_name=_(u'Licence Number'))
    type = models.CharField(default=None, max_length=30, verbose_name=_(u'Type'))
    engine_num = models.CharField(default=None, max_length=30, verbose_name=_(u'Engin Number'))
    registration_date = models.DateField(default=None, null=True, verbose_name=_(u'Registration Date'))
    number_of_seats = models.CharField(default=None, max_length=30, verbose_name=_(u'Number of Seats'))
    color = models.CharField(default=None, max_length=30, verbose_name=_(u'Color'))
    make = models.CharField(default=None, max_length=30, verbose_name=_(u'make'))
    model = models.CharField(default=None, max_length=30, verbose_name=_(u'Model'))
    year = models.CharField(default=None, max_length=30, verbose_name=_(u'Year'))
    body_type = models.CharField(default=None, max_length=30, verbose_name=_(u'Body Type'))
    gas_type = models.CharField(default=None, max_length=30, verbose_name=_(u'Gas Type'))
    date_of_purchase = models.DateField(default=None, max_length=30, verbose_name=_(u'Date of Purchase'))
    km_read_at_purchase = models.IntegerField(default=None, verbose_name=_(u'Km Read at Purchase'))
    licence_renewal_date = models.DateField(default=None, max_length=30, verbose_name=_(u'Licence Renewal Date'))
    insurance_renewal_date = models.DateField(default=None, max_length=30, verbose_name=_(u'Insurance Renewal Date'))

    class Meta:
        ordering = ['licence_num']
        verbose_name = _(u'Vehicle')
        verbose_name_plural = _(u'Vehicles')

    def __str__(self):
        return self.licence_num


class VehicleStatus(models.Model):

    vehicle = models.ForeignKey(Vehicle)
    status = models.CharField(max_length=30, verbose_name=_(u'Status'))
    timestamp = models.DateTimeField(auto_now_add=True)
    date = models.DateField(default=datetime.today)

    def __str__(self):
        return self.status


class VehicleDriver(models.Model):

    vehicle = models.ForeignKey(Vehicle)
    driver = models.ForeignKey(Driver)
    timestamp = models.DateTimeField(auto_now_add=True)
    start_date = models.DateField(default=datetime.today)
    end_date = models.DateField(null=True)

    def __str__(self):
        return self.vehicle + " " + self.driver + " "
        + self.start_date + " " + self.end_date

gpsdevices/forms.py
from __future__ import absolute_import

from django import forms
from gpsdevices.models import GPSDevice
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Field
from crispy_forms.bootstrap import FormActions


class GPSDeviceForm(forms.ModelForm):
    name = forms.CharField(label='Device Name', widget=forms.TextInput())
    type = forms.CharField(label='Device Type', widget=forms.TextInput())
    imei = forms.CharField(label='Device IMEI', widget=forms.TextInput())
    sim_num = forms.CharField(label='SIM Card Number', widget=forms.TextInput())
    purchase_date = forms.DateField(label='Purchase_Date', widget=forms.DateInput(attrs={'type': 'date'}))
    assigned_to = forms.CharField(label='Assign To', widget=forms.TextInput())
    status = forms.ChoiceField(label='Status', choices=(('Installed', 'Installed'), ('Not Installed', 'Not Installed')))

    # Uni-form
    helper = FormHelper()
    helper.form_class = 'form-horizontal col col-md-12'
    helper.form_method = 'POST'
    helper.field_class = 'col col-md-8'
    helper.label_class = 'col col-md-4'

    helper.layout = Layout(

        Div(
            Div(
                Field('name', css_class='form-control'),
                Field('type', css_class='form-control'),
                Field('imei', css_class='form-control'),
                Field('sim_num', css_class='form-control'),
                Field('purchase_date', css_class='form-control'),
                Field('assigned_to', css_class='form-control'),
                Field('status', css_class='form-control'), css_class='col col-md-6',
            ),
            Div(
                HTML('<br/>'),
                FormActions(
                    Submit('save', 'Save', css_class='btn btn-primary'),
                    Submit('cancel', 'Cancel', css_class='btn btn-danger'),
                ), css_class='col col-md-6 col-offset-2',
            ), css_class='row',
        ),
    )

    class Meta:
        model = GPSDevice
        fields = '__all__'

gpsdevices/views.py
from django.core.urlresolvers import reverse, reverse_lazy
from django.shortcuts import render
from django.utils.translation import ugettext as _
from django.views.generic import (ListView, CreateView, UpdateView, DeleteView, DetailView,)

from gpsdevices.models import GPSDevice
from gpsdevices.forms import GPSDeviceForm

from braces.views import LoginRequiredMixin, FormMessagesMixin


class GPSDeviceListView(ListView):

    model = GPSDevice
    template_name = 'gpsdevice/gpsdevices_list.html'


class CreateGPSDeviceView(FormMessagesMixin, CreateView):

    extra_context = {'object_name': _(u'GPSDevice')}
    model = GPSDevice
    template_name = 'gpsdevice/add_gpsdevice.html'
    form_class = GPSDeviceForm
    template_name = 'gpsdevice/add_gpsdevice.html'
    form_valid_message = 'GPS Device was successfully added!'
    form_invalid_message = 'Some errors were found during form submission. Please check the data and resubmit.'

    def get_success_url(self):
        return reverse('gpsdevices_list')

    def get_context_data(self, **kwargs):
        context = super(CreateGPSDeviceView, self).get_context_data(**kwargs)
        context['target'] = reverse('add_gpsdevice')

        return context


class UpdateGPSDeviceView(FormMessagesMixin, UpdateView):

    model = GPSDevice
    form_class = GPSDeviceForm

    template_name = 'gpsdevice/edit_gpsdevice.html'
    form_valid_message = 'Device records updated successfully'

    def get_success_url(self):
        return reverse('gpsdevices_list')

    def get_context_data(self, **kwargs):
        context = super(UpdateGPSDeviceView, self).get_context_data(**kwargs)
        context['target'] = reverse('edit_gpsdevice', kwargs={'pk': self.get_object().id})
        return context


class DeleteGPSDeviceView(DeleteView):
    model = GPSDevice
    success_url = reverse_lazy('gpsdevices_list')


class GPSDeviceView(DetailView):

    model = GPSDevice
    template_name = 'gpsdevice/gpsdevice.html'


def view_gpsdevice(request, pk):
    
    gpsdevice = GPSDevice.objects.get(id=pk)
    context = dict(
        gpsdevice=gpsdevice,
    )
    return render(request, 'gpsdevice/view_gpsdevice.html', context)

templates/gpsdevice/add_gpsdevice.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}New GPS Device{% endblock %}
{% block sub-menu %}
    <div class="navbar top-menu">
		<ul class="nav navbar-nav sub-menu">
            <a href="{% url 'gpsdevices_list' %}">
                <button type="button" class="btn btn-default btn-md">
                    <span class="glyphicon glyphicon-list-alt"></span>&nbsp;GPS Devices List
                </button>
            </a>
            <a href="{% url 'add_gpsdevice' %}">
                <button type="button" class="btn btn-default btn-md active">
                    <span class="glyphicon glyphicon-plus"></span>&nbsp;New GPS Device
                </button>
            </a>
        </ul>
	</div>
{% endblock %}
{% block content %}
     <style>
        .panel-body {
            height: 70vh;
            overflow: auto;
        }
     </style>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                       <strong style="font-size: medium">New Driver Details</strong>
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        {% csrf_token %}
                        {% crispy form %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/gpsdevice/edit_gpsdevice.html
{%extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}GPS Devices{% endblock %}
{% block sub-menu %}
    <div class="navbar top-menu">
		<ul class="nav navbar-nav sub-menu">
            <a href="{% url 'gpsdevices_list' %}">
                <button type="button" class="btn btn-default btn-md">
                    <span class="glyphicon glyphicon-list-alt"></span>&nbsp;GPS Devices
                </button>
            </a>
            <a href="{% url 'add_gpsdevice' %}">
                <button type="button" class="btn btn-default btn-md">
                    <span class="glyphicon glyphicon-plus"></span>&nbsp;New GPS Device
                </button>
            </a>
            <a href="{% url 'edit_gpsdevice' pk=gpsdevice.id %}">
                <button type="button" class="btn btn-default btn-md active">
                    <span class="glyphicon glyphicon-plus"></span>&nbsp;Edit GPS Device
                </button>
            </a>
        </ul>
	</div>
{% endblock %}
{% block content %}
     <style>
        .panel-body {
            height: 70vh;
            overflow: auto;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                       {% if object.id %}
                            <strong style="font-size: medium">Edit details for {{ object.name}} {{ object.type }}</strong>
                        {% else %}
                            <strong style="font-size: medium">New GPS Device Details</strong>
                        {% endif %}
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        {% csrf_token %}
                        {% crispy form %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/gpsdevice/gpsdevice.html
{%extends 'base.html' %}
{% block title %}{{ driver.first_name }} {{ driver.last_name }}{% endblock %}
{% block content %}
    <div class="navbar top-menu">
		<ul class="nav navbar-nav sub-menu">
            <a href="{% url 'add_asset' %}">
            <button type="button" class="btn btn-default btn-md">
                <span class="glyphicon glyphicon-plus"></span>Add Driver
            </button>
            </a>
             <a href="{% url 'edit_asset' pk=driver.id %}">
            <button type="button" class="btn btn-default btn-md">
                <span class="glyphicon glyphicon-plus"></span>Edit Driver
            </button>
            </a>
        </ul>
	</div>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                       {{ vehicle.plate_num }}
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <ul>
                            <li>Driver: {{ driver.first_name }} {{ driver.last_name }}</li>
                            <li>Email address: {{ driver.email }}</li>
                            <li>Vehicle: {{ vehicle.vehicle_set.all }}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/gpsdevice/gpsdevices_list.html
{%extends 'base.html' %}
{% block title %}GPS Devices{% endblock %}
{% block sub-menu %}
    <div class="navbar top-menu">
		<ul class="nav navbar-nav sub-menu">
            <a href="{% url 'gpsdevices_list' %}">
                <button type="button" class="btn btn-default btn-md active">
                    <span class="glyphicon glyphicon-list-alt"></span>&nbsp;GPS Devices
                </button>
            </a>
            <a href="{% url 'add_gpsdevice' %}">
                <button type="button" class="btn btn-default btn-md">
                    <span class="glyphicon glyphicon-plus"></span>&nbsp;New GPS Device
                </button>
            </a>
        </ul>
	</div>
{% endblock %}
{% block content %}
     <style>
        .panel-body {
            height: 70vh;
            overflow: auto;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <strong style="font-size: medium">GPS Device List</strong>
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-12">
                                {% ifequal gpsdevice 0%}
                                    <span class="alert alert-info"><i class="glyphicon glyphicon-info-sign"></i>&nbsp;<strong>No GPS Devices added yet. Please add new GPS Devices</strong></span>
                                {% else %}
                                <table class="table table-striped table-condensed">
                                    <tr>
                                       <th align="center">ID</th>
                                        <th align="center">Asset Name</th>
                                        <th align="center">Type</th>
                                        <th align="center">IMEI</th>
                                        <th align="center">Sim Number</th>
                                        <th align="center">Assigned To</th>
                                        <th align="center">Options</th>
                                    </tr>
                                    <tbody>
                                        {% for gpsdevice in object_list %}
                                           <tr>
                                                <td>{{ gpsdevice.id }}</td>
                                                <td>{{ gpsdevice.name }}</td>
                                                <td>{{ gpsdevice.type}}</td>
                                                <td>{{ gpsdevice.imei }}</td>
                                                <td>{{ gpsdevice.sim_num }}</td>
                                                <td>{{ gpsdevice.assigned_to }}</td>
                                                <td align="center">
                                                    <a href="{% url 'view_gpsdevice' pk=gpsdevice.id %}"><button class="btn btn-success btn-sm">View</button></a>
                                                    <a href="{% url 'edit_gpsdevice' pk=gpsdevice.id %}"><button class="btn btn-primary btn-sm">Edit</button></a>
                                                    <a href=""><button class="btn btn-danger btn-sm">Delete</button></a>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            {% endifequal %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/gpsdevice/view_gpsdevice.html
{%extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}GPS Devices{% endblock %}
{% block sub-menu %}
    <div class="navbar top-menu">
		<ul class="nav navbar-nav sub-menu">
            <a href="{% url 'gpsdevices_list' %}">
                <button type="button" class="btn btn-default btn-md">
                    <span class="glyphicon glyphicon-list-alt"></span>&nbsp;GPS Devices
                </button>
            </a>
            <a href="{% url 'add_gpsdevice' %}">
                <button type="button" class="btn btn-default btn-md">
                    <span class="glyphicon glyphicon-plus"></span>&nbsp;New GPS Device
                </button>
            </a>
            <a href="{% url 'edit_gpsdevice' pk=gpsdevice.id %}">
                <button type="button" class="btn btn-default btn-md">
                    <span class="glyphicon glyphicon-plus"></span>&nbsp;Edit GPS Device
                </button>
            </a>
        </ul>
	</div>
{% endblock %}
{% block content %}
     <style>
        .panel-body {
            height: 70vh;
            overflow: auto;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">

                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                         <div class="row">
                            <div class="col-md-6">
                                <table class="table table-striped table-condensed">
                                    <tbody>
                                        <tr>
                                            <td><strong>Device Name :</strong></td>
                                            <td>{{ gpsdevice.name }}</td>
                                        </tr>
                                        <tr>
                                            <td><strong>Type : </strong></td>
                                            <td>{{ gpsdevice.type}}</td>
                                        </tr>
                                        <tr>
                                            <td><strong>IMEI :</strong></td>
                                            <td>{{ gpsdevice.imei }}</td>
                                        </tr>
                                        <tr>
                                            <td><strong>SIM Card :</strong></td>
                                            <td>{{ gpsdevice.sim_num }}</td>
                                        </tr>
                                        <tr>
                                            <td><strong>Date purchased :</strong></td>
                                            <td>{{ gpsdevice.purchase_date }}</td>
                                        </tr>
                                        <tr>
                                            <td><strong>Vehicle installed :</strong></td>
                                            <td>{{ gpsdevice.assigned_to }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}